---
- name: Deploy Dino Dush backend
  hosts: app
  vars:
    non_prod_namespace: dino-dush-non-prod
    prod_namespace: dino-dush-prod
  tasks:
  - include_vars: "{{ inventory_dir }}/../encrypted-vars.yml"
  - include_role:
      name: openshift-applier/roles/openshift-applier
