---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: git-secret-template
  credential.sync.jenkins.openshift.io: "true"
metadata:
  name: git-secret-template
objects:
- apiVersion: v1
  data:
    password: ${PASSWORD}
    username: ${USERNAME}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: ${NAME}
  type: kubernetes.io/basic-auth
parameters:
- name: NAME
  value: git-auth
- name: USERNAME
  require: true
- name: PASSWORD
  require: true
